Running "main" (4 tests)...
suite_strlen_test.c:9: Failure: our_tests -> returns_five_for_hello 
	Expected [strlen("Hiya")] to [equal] [5]
		actual value:			[4]
		expected value:			[5]

Completed "our_tests": 1 pass, 1 failure, 0 exceptions.
suite_person_test.c:29: Failure: person_tests -> can_add_person_to_database 
	Expected [get_person_name(found)] to [equal string] ["Fred"]
		actual value:			["(null)"]
		expected to equal:		["Fred"]

suite_person_test.c:38: Failure: person_tests -> cannot_add_duplicate_person 
	Expected [save_person(duplicate)] to [be false]

Completed "person_tests": 2 passes, 3 failures, 0 exceptions.
Completed "main": 2 passes, 3 failures, 0 exceptions.
